"""Postprocesado opcional de proyectos generados mediante un agente externo."""

import os
import shlex
import subprocess
from pathlib import Path

from .parsing import DefinitionError

RULE_FILES = (
    "AGENTS.md",
    "docs/java-style.md",
    "docs/annotations.md",
    "docs/layered-architecture.md",
    "docs/controllers.md",
    "docs/mappers.md",
    "docs/exceptions.md",
    "docs/testing.md",
    "docs/logging.md",
)

AGENT_COMMAND_ENV = "CRUD_AUTOMATION_AGENT_COMMAND"


def _repository_root():
    return Path(__file__).resolve().parent.parent


def load_agent_rules(root=None):
    """Carga las reglas del repositorio del generador; nunca del proyecto generado."""
    rules_root = Path(root) if root else _repository_root()
    sections = []

    for relative_path in RULE_FILES:
        path = rules_root / relative_path
        if not path.is_file():
            raise DefinitionError(
                f"No se puede aplicar el agente: falta la regla '{relative_path}'."
            )
        sections.append(f"# Source: {relative_path}\n\n{path.read_text(encoding='utf-8').strip()}")

    return "\n\n---\n\n".join(sections)


def build_agent_prompt(project_dir, rules_text=None):
    """Construye el encargo que recibe el agente tras generar el microservicio."""
    project_path = Path(project_dir).resolve()
    rules = rules_text if rules_text is not None else load_agent_rules()

    return f"""You are post-processing a Spring Boot project generated by crud-automation.

Target project: {project_path}

Refactor the generated project so that its Java/Spring Boot production code and tests comply with the rules below.

Important constraints:
- Work only inside the target project.
- Do NOT copy AGENTS.md or any of the docs/*.md rule files into the target project.
- Preserve the requested public API and domain behaviour unless a rule explicitly requires a structural refactor.
- Preserve database migrations and externally visible endpoint semantics.
- Inspect the existing generated code before editing it.
- Apply the rules to the generated implementation, not merely as documentation.
- Run the relevant formatter and tests after editing when the project provides them.
- If two rules conflict, AGENTS.md has precedence over topic files.

Repository rules to apply:

{rules}
"""


def resolve_agent_command(command=None):
    value = command or os.environ.get(AGENT_COMMAND_ENV)
    if not value or not value.strip():
        raise DefinitionError(
            "--apply-agent-rules necesita --agent-command o la variable "
            f"{AGENT_COMMAND_ENV}. El comando debe aceptar el prompt por stdin."
        )

    return value.strip()


def apply_agent_rules(project_dir, command=None):
    """Ejecuta un agente externo en el proyecto y le pasa las reglas por stdin.

    El comando se ejecuta con cwd apuntando al microservicio generado. Se admite
    el marcador {project_dir} dentro del comando para herramientas que necesiten
    recibir explícitamente la ruta del proyecto.
    """
    project_path = Path(project_dir).resolve()
    if not project_path.is_dir():
        raise DefinitionError(
            f"No se puede aplicar el agente: '{project_dir}' no es un directorio generado."
        )

    command_template = resolve_agent_command(command)
    rendered_command = command_template.replace("{project_dir}", str(project_path))
    arguments = shlex.split(rendered_command)
    prompt = build_agent_prompt(project_path)

    try:
        completed = subprocess.run(
            arguments,
            cwd=project_path,
            input=prompt,
            text=True,
            check=False,
        )
    except FileNotFoundError as error:
        raise DefinitionError(
            f"No se pudo ejecutar el agente '{arguments[0]}': comando no encontrado."
        ) from error
    except OSError as error:
        raise DefinitionError(f"No se pudo ejecutar el agente: {error}") from error

    if completed.returncode != 0:
        raise DefinitionError(
            f"El agente terminó con código {completed.returncode}; "
            "el proyecto generado se conserva para poder inspeccionarlo."
        )

    return project_path
