#!/usr/bin/env python3
"""Generate the rft-observability-item-batch microservice from scratch.

Recreates the full project (Maven build, Spring Batch T32A job source,
Docker/Compose, CI, README) as it exists today. IDE metadata (.idea/) and
build output (target/, output/) are intentionally not reproduced -- they
are generated by your IDE / Maven, not part of the service itself.

Usage:
    python generate_crud.py --batch [target_dir] [--force]
    python -m crud_generator.generate_service [target_dir] [--force]

    target_dir   Directory to create the project in (default:
                 "rft-observability-item-batch", created if missing).
    --force      Overwrite files that already exist in target_dir.
"""

import argparse
import sys
from pathlib import Path

from .parsing import DefinitionError

DEFAULT_TARGET = "rft-observability-item-batch"

FILES: dict[str, str] = {}

# --------------------------------------------------------------------------
# Root-level files
# --------------------------------------------------------------------------

FILES[".env.example"] = r'''# Copy to .env and adjust as needed. Never commit the real .env file.

APP_PORT=9001
SPRING_PROFILES_ACTIVE=docker

# Primary datasource (JdbcTemplate, Spring Batch job repository).
# Defaults to an ephemeral in-memory H2 instance; point it at a real
# database for anything beyond local/demo use.
SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
SPRING_DATASOURCE_USERNAME=sa
SPRING_DATASOURCE_PASSWORD=

# T32A job parameters.
APP_JOBS_T32A_END_PERIOD=2026-03-31
APP_JOBS_T32A_REPORTING_DATE=2026-04-30
'''

FILES[".gitignore"] = r'''target/
*.class
.vscode/
.env
/output/
source/output/
'''

FILES[".gitlab-ci.yml"] = r'''image: artifactory.six-group.net/maven:3.8.3-openjdk-17

include:
- project: $PIPELINE_TEMPLATES_REPO_PATH
  ref: $PIPELINE_TEMPLATES_REPO_BRANCH
  file: $PIPELINE_TEMPLATES_BACKEND_JAVA_FILENAME

variables:
  SERVICE_LOCATION: ''
  HELM_CHART_VALUES_LOCATION: rft-data-bec
  IMAGE_LOCATION: backend
  JAVA_VERSION: 17
'''

FILES["README.md"] = r'''# EMIR REFIT Batch

Servicio Spring Boot que ejecuta los jobs de reporting regulatorio EMIR REFIT
(T-32a, T-32b, T-32c, T-33a) contra Impala y escribe el resultado en CSV.
Los jobs se lanzan bajo demanda vía API REST o de forma programada (scheduler).

## Arranque

    mvn spring-boot:run

La app arranca en http://localhost:8080 y se queda escuchando. El auto-arranque
de jobs está deshabilitado (spring.batch.job.enabled: false); los jobs se lanzan
vía API o cron.

## API REST

| Método | Ruta | Descripción |
|--------|------|-------------|
| GET  | /api/jobs | Lista los jobs disponibles |
| POST | /api/jobs/{jobName}/run | Lanza un job con parámetros |
| GET  | /api/jobs/executions/{executionId} | Estado de una ejecución |

### Swagger UI

- Swagger UI: http://localhost:8080/swagger-ui.html
- Spec JSON (generado en runtime): http://localhost:8080/v3/api-docs
- Spec estático diseñado: src/main/resources/openapi.yaml

### Ejemplos

    # Listar jobs
    curl http://localhost:8080/api/jobs

    # T-32a
    curl -X POST http://localhost:8080/api/jobs/t32aJob/run \
      -H "Content-Type: application/json" \
      -d '{"fecha":"2026-04-30","endPeriod":"2026-03-31"}'

    # T-32c
    curl -X POST http://localhost:8080/api/jobs/t32cJob/run \
      -H "Content-Type: application/json" \
      -d '{"fecha":"2026-04-30","startDate":"2026-01-01 00:00:00.000","endDate":"2026-03-31 00:00:00.000"}'

    # T-33a con ruta de salida personalizada
    curl -X POST http://localhost:8080/api/jobs/t33aJob/run \
      -H "Content-Type: application/json" \
      -d '{"reportingDate":"2026-04-15","endDate":"2026-03-31","outputPath":"/data/out/item33a.csv"}'

    # Estado de ejecución
    curl http://localhost:8080/api/jobs/executions/42

## Parámetros por job

| Job | Parámetros (body JSON) |
|-----|------------------------|
| t32aJob | fecha, endPeriod |
| t32bJob | fecha, endPeriod |
| t32cJob | fecha, startDate, endDate |
| t33aJob | reportingDate, endDate |

outputPath es opcional en todos.

## Qué está parametrizado

Por API (runtime, cambian en cada ejecución):
- Todas las fechas (fecha, endPeriod, startDate, endDate, reportingDate)
- Ruta de salida del CSV (outputPath)

Por configuración (application.yml, cambian entre entornos int/prod):
- Nombres de schema/tabla de cada query (emir.tables.*)
- Lista de países EEA (emir.eea-countries)
- Valores estáticos TR_CODE y REGULATION_REFERENCE (emir.tr-code, emir.regulation-reference)
- Conexión Impala (app.impala.*)
- Rutas de salida por defecto (app.output.*)
- Cron y fechas por defecto del scheduler (batch.schedule.*, batch.defaults.*)

No parametrizado (lógica de negocio del reporte):
- Los códigos de estado en los CASE WHEN rcncltnsts IN (...), categorías de
  calidad de dato, etc. Son la semántica del reporte regulatorio; cambiarlos
  alteraría el significado de la salida, así que se mantienen fijos en el SQL.

## Scheduler

JobScheduler lanza los 4 jobs con las fechas por defecto de batch.defaults.*
según el cron batch.schedule.cron (por defecto 02:00 cada día). Reutiliza el
mismo JobLaunchService que la API.

## Docker

> Estado actual del código: solo el job T-32a está implementado (reader =
> consulta Impala/Kudu, processor = mapeo DTO → entidad, writer = CSV), y se
> lanza automáticamente al arrancar (`JobRunnerConfig`), no vía API — el
> resto de esta sección de README (API REST, scheduler) es el diseño
> objetivo, aún no implementado. La app escucha en el puerto **9001**, no
> 8080. Al completar el job, el proceso llama a `System.exit()`: el
> contenedor arranca, ejecuta el job y termina con código 0 — es el
> comportamiento esperado de un job batch, no un fallo.

### Prerrequisitos

- Docker y Docker Compose.

### Variables de entorno

Copia `.env.example` a `.env` y ajusta si hace falta:

| Variable | Descripción | Por defecto |
|----------|-------------|-------------|
| `APP_PORT` | Puerto expuesto en el host | `9001` |
| `SPRING_DATASOURCE_URL/USERNAME/PASSWORD` | Datasource único (JdbcTemplate, repositorio de Spring Batch, consultas T-32a); apúntalo a Impala/Kudu real en un entorno de verdad | H2 en memoria |
| `APP_JOBS_T32A_END_PERIOD` / `APP_JOBS_T32A_REPORTING_DATE` | Parámetros del job T-32a | `2026-03-31` / `2026-04-30` |

Ningún secreto real debe ir en `.env.example`; `.env` está en `.gitignore`.

### Comandos

    docker compose build
    docker compose up -d
    docker compose ps
    docker compose logs -f app
    docker compose down

Reset completo (borra también los volúmenes/datos locales):

    docker compose down -v

### Verificación

- El CSV generado aparece en `./output/item32a-output.csv` (montado desde el
  contenedor).
- Mientras el contenedor está arriba: `curl http://localhost:9001/actuator/health`.
- `docker compose ps` mostrará `Exited (0)` tras completar el job — así se
  confirma que terminó bien, no que algo falló.
'''

FILES["docker-compose.yml"] = r'''services:
  app:
    build:
      context: ./source
    image: rft-observability-item-batch:local
    container_name: rft-observability-item-batch
    ports:
      - "${APP_PORT:-9001}:9001"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:h2:mem:testdb}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-sa}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-}
      APP_JOBS_T32A_END_PERIOD: ${APP_JOBS_T32A_END_PERIOD:-2026-03-31}
      APP_JOBS_T32A_REPORTING_DATE: ${APP_JOBS_T32A_REPORTING_DATE:-2026-04-30}
      APP_OUTPUT_T32A_CSV: /app/output/item32a-output.csv
    volumes:
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9001/actuator/health"]
      interval: 10s
      timeout: 3s
      start_period: 20s
      retries: 5
    networks:
      - rft-network

networks:
  rft-network:
    name: rft-observability-item-batch-network
'''

FILES["sonar-project.properties"] = r'''sonar.language=java
sonar.coverage.jacoco.xmlReportPaths=source/target/site/jacoco/jacoco.xml
sonar.host.url=${env.SONARQUBE_HOST_URL}
sonar.login=${env.SONARQUBE_TOKEN}
sonar.projectKey=${env.CI_PROJECT_NAME}
sonar.qualitygate.wait=true
sonar.java.binaries=source/target/classes
sonar.java.test.binaries=source/target/test-classes
sonar.sources=source/src/main/java
sonar.tests=source/src/test/java
'''

# --------------------------------------------------------------------------
# source/ - Docker & build
# --------------------------------------------------------------------------

FILES["source/.dockerignore"] = r'''target/
output/
.git/
.idea/
.vscode/
*.iml
*.log
.env
.flattened-pom.xml
'''

FILES["source/Dockerfile"] = r'''# syntax=docker/dockerfile:1

# ---- Build stage ----------------------------------------------------------
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B clean verify -DskipITs

# ---- Runtime stage ----------------------------------------------------------
FROM eclipse-temurin:17-jre
WORKDIR /app

RUN addgroup --system app && adduser --system --ingroup app app

COPY --from=build /app/target/*.jar app.jar
RUN mkdir -p /app/output && chown -R app:app /app

USER app

EXPOSE 9001

HEALTHCHECK --interval=10s --timeout=3s --start-period=20s --retries=5 \
    CMD wget -q -O - http://localhost:9001/actuator/health | grep -q '"status":"UP"' || exit 1

ENTRYPOINT ["java", "-jar", "app.jar"]
'''

FILES["source/pom.xml"] = r'''<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sixgroup.refit.observability</groupId>
    <artifactId>rft-observability-item-batch</artifactId>
    <version>${revision}${sha1}${changelist}</version>

    <properties>
        <revision>0.0.1</revision>
        <sha1></sha1>
        <changelist>-SNAPSHOT</changelist>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <java.version>17</java.version>
        <spring-boot.version>3.5.16</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-batch</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.batch</groupId>
            <artifactId>spring-batch-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
'''

# --------------------------------------------------------------------------
# source/src/main/java - application source
# --------------------------------------------------------------------------

FILES["source/src/main/java/com/sixgroup/refit/observability/BatchProcessingDemoApplication.java"] = r'''package com.sixgroup.refit.observability;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;

@SpringBootApplication
@ConfigurationPropertiesScan
public class BatchProcessingDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(BatchProcessingDemoApplication.class, args);
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/batch/Item32ABatchConfig.java"] = r'''package com.sixgroup.refit.observability.batch;

import com.sixgroup.refit.observability.config.Item32Properties;
import com.sixgroup.refit.observability.dto.Item32ACountsDto;
import com.sixgroup.refit.observability.model.Item32AData;
import com.sixgroup.refit.observability.processor.Item32AProcessor;
import com.sixgroup.refit.observability.reader.Item32AReader;
import com.sixgroup.refit.observability.sql.Item32ADataFinderService;
import com.sixgroup.refit.observability.writer.Item32ACsvWriterFactory;
import lombok.RequiredArgsConstructor;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.ItemReader;
import org.springframework.batch.item.file.FlatFileItemWriter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.PlatformTransactionManager;

/**
 * Wires the T32A job: reader ({@link Item32AReader}) runs the Impala/Kudu
 * query, processor ({@link Item32AProcessor}) maps the DTO into the entity,
 * writer ({@link Item32ACsvWriterFactory}) writes it out as CSV.
 */
@Configuration
@RequiredArgsConstructor
public class Item32ABatchConfig {

    private final Item32ADataFinderService item32ADataFinderService;
    private final Item32Properties item32Properties;

    @Bean
    @StepScope
    public ItemReader<Item32ACountsDto> t32aReader(
            @Value("#{jobParameters['endPeriod']}") String endPeriod) {
        return new Item32AReader(item32ADataFinderService, endPeriod);
    }

    @Bean
    @StepScope
    public ItemProcessor<Item32ACountsDto, Item32AData> t32aProcessor(
            @Value("#{jobParameters['reportingDate']}") String reportingDate) {
        return new Item32AProcessor(item32Properties, reportingDate);
    }

    @Bean
    @StepScope
    public FlatFileItemWriter<Item32AData> t32aCsvWriter(
            @Value("#{jobParameters['outputPath'] ?: '${app.output.t32a-csv:output/item32a-output.csv}'}") String outputPath) {
        return Item32ACsvWriterFactory.create(outputPath);
    }

    @Bean
    public Step t32aStep(
            JobRepository jobRepository,
            PlatformTransactionManager transactionManager,
            ItemReader<Item32ACountsDto> t32aReader,
            ItemProcessor<Item32ACountsDto, Item32AData> t32aProcessor,
            FlatFileItemWriter<Item32AData> t32aCsvWriter) {
        return new StepBuilder("t32aStep", jobRepository)
                .<Item32ACountsDto, Item32AData>chunk(1, transactionManager)
                .reader(t32aReader)
                .processor(t32aProcessor)
                .writer(t32aCsvWriter)
                .build();
    }

    @Bean
    public Job t32aJob(JobRepository jobRepository, Step t32aStep) {
        return new JobBuilder("t32aJob", jobRepository)
                .start(t32aStep)
                .build();
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/config/DatasourceSchemaProperties.java"] = r'''package com.sixgroup.refit.observability.config;

import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Getter
@Setter
@ConfigurationProperties(prefix = "component-config.kududb")
public class DatasourceSchemaProperties {
    @NotNull
    private String controlRefitSchema;

    @NotNull
    private String transcSchema;
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/config/Item32Properties.java"] = r'''package com.sixgroup.refit.observability.config;

import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Getter
@Setter
@ConfigurationProperties("component-config.item32")
public class Item32Properties {
    @NotNull
    private Item32AProperties item32Aproperties;

    @Getter
    @Setter
    public static class Item32AProperties {

        @NotNull
        private Long initialTotalTradesNew;
        @NotNull
        private Long initialTotalTradesAll;
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/config/JobRunnerConfig.java"] = r'''package com.sixgroup.refit.observability.config;

import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class JobRunnerConfig {

    @Bean
    public CommandLineRunner runJob(
            JobLauncher jobLauncher,
            @Qualifier("t32aJob") Job t32aJob,
            ApplicationContext applicationContext,
            @Value("${app.jobs.t32a.end-period}") String endPeriod,
            @Value("${app.jobs.t32a.reporting-date}") String reportingDate) {

        return args -> {

            JobParameters jobParameters = new JobParametersBuilder()
                    .addString("endPeriod", endPeriod)
                    .addString("reportingDate", reportingDate)
                    .addLong("runId", System.currentTimeMillis())
                    .toJobParameters();

            JobExecution execution = jobLauncher.run(t32aJob, jobParameters);

            int exitCode = SpringApplication.exit(applicationContext,
                    () -> execution.getStatus() == BatchStatus.COMPLETED ? 0 : 1);
            System.exit(exitCode);
        };
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/dto/Item32ACountsDto.java"] = r'''package com.sixgroup.refit.observability.dto;

import lombok.*;

/**
 * Raw counts as returned by the Kudu/Impala queries in
 * {@link com.sixgroup.refit.observability.sql.Item32ADataFinderService},
 * before the business enrichment (initial totals, reporting date) that
 * turns them into an {@link com.sixgroup.refit.observability.model.Item32AData} entity.
 */
@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Item32ACountsDto {
    private Long tradesFromImpala;
    private Long reportsFromKudu;
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/model/Item32AData.java"] = r'''package com.sixgroup.refit.observability.model;

import lombok.*;

@Getter
@Setter
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Item32AData {
    private String reportingDate;
    private Long totalNrTrades;
    private Long totalNrReports;
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/processor/Item32AProcessor.java"] = r'''package com.sixgroup.refit.observability.processor;

import com.sixgroup.refit.observability.config.Item32Properties;
import com.sixgroup.refit.observability.dto.Item32ACountsDto;
import com.sixgroup.refit.observability.model.Item32AData;
import lombok.RequiredArgsConstructor;
import org.springframework.batch.item.ItemProcessor;

/**
 * Turns the raw Kudu/Impala counts DTO into the Item32AData entity by
 * applying the business rule (adding each series' initial total) and
 * stamping the reporting date.
 */
@RequiredArgsConstructor
public class Item32AProcessor implements ItemProcessor<Item32ACountsDto, Item32AData> {

    private final Item32Properties item32Properties;
    private final String reportingDate;

    @Override
    public Item32AData process(Item32ACountsDto counts) {
        final long totalNrTrades = counts.getTradesFromImpala()
                + item32Properties.getItem32Aproperties().getInitialTotalTradesNew();
        final long totalNrReports = counts.getReportsFromKudu()
                + item32Properties.getItem32Aproperties().getInitialTotalTradesAll();

        return Item32AData.builder()
                .reportingDate(reportingDate)
                .totalNrTrades(totalNrTrades)
                .totalNrReports(totalNrReports)
                .build();
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/reader/Item32AReader.java"] = r'''package com.sixgroup.refit.observability.reader;

import com.sixgroup.refit.observability.dto.Item32ACountsDto;
import com.sixgroup.refit.observability.sql.Item32ADataFinderService;
import lombok.RequiredArgsConstructor;
import org.springframework.batch.item.ItemReader;

import java.util.concurrent.atomic.AtomicBoolean;

/**
 * The reader IS the Item T32A query: it delegates to
 * {@link Item32ADataFinderService#fetchCounts}, which runs the two
 * Impala/Kudu COUNT queries, and hands the single raw-counts DTO to the
 * step once before signalling end-of-data.
 */
@RequiredArgsConstructor
public class Item32AReader implements ItemReader<Item32ACountsDto> {

    private final Item32ADataFinderService item32ADataFinderService;
    private final String endPeriod;
    private final AtomicBoolean alreadyRead = new AtomicBoolean(false);

    @Override
    public Item32ACountsDto read() {
        if (alreadyRead.compareAndSet(false, true)) {
            return item32ADataFinderService.fetchCounts(endPeriod);
        }
        return null;
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/sql/Item32ADataFinderService.java"] = r'''package com.sixgroup.refit.observability.sql;

import com.sixgroup.refit.observability.config.DatasourceSchemaProperties;
import com.sixgroup.refit.observability.dto.Item32ACountsDto;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@RequiredArgsConstructor
public class Item32ADataFinderService {

    private static final String TOTAL_NR_TRADES_QUERY = """
            SELECT COUNT(*) AS TOTAL_NR_TRADES_RECEIVED_FROM_START
            FROM %s.opr_data
            WHERE actntp IN ('NEWT', 'POSC')
            AND rptgtmstmpdt <= ?
            """;

    private static final String TOTAL_NR_REPORTS_QUERY = """
            SELECT COUNT(*) AS TOTAL_NR_REPORTS_RECEIVED_FROM_START
            FROM %s.record_status
            WHERE receiveddt <= ?
            """;

    private final JdbcTemplate jdbcTemplate;
    private final DatasourceSchemaProperties schemaProperties;

    public Item32ACountsDto fetchCounts(final String endPeriod) {
        log.trace("Running Item T32A raw counts query for endPeriod: {}", endPeriod);

        final long tradesFromImpala = countFor(
                TOTAL_NR_TRADES_QUERY.formatted(schemaProperties.getTranscSchema()), endPeriod);
        final long reportsFromKudu = countFor(
                TOTAL_NR_REPORTS_QUERY.formatted(schemaProperties.getControlRefitSchema()), endPeriod);

        final Item32ACountsDto counts = Item32ACountsDto.builder()
                .tradesFromImpala(tradesFromImpala)
                .reportsFromKudu(reportsFromKudu)
                .build();

        log.trace("Item32A raw counts fetched successfully: {}", counts);
        return counts;
    }

    private long countFor(final String query, final String endPeriod) {
        log.trace("Sending query to Impala [endPeriod={}]: {}", endPeriod, query);
        final Long count = jdbcTemplate.queryForObject(query, Long.class, endPeriod);
        return count != null ? count : 0L;
    }
}
'''

FILES["source/src/main/java/com/sixgroup/refit/observability/writer/Item32ACsvWriterFactory.java"] = r'''package com.sixgroup.refit.observability.writer;

import com.sixgroup.refit.observability.model.Item32AData;
import org.springframework.batch.item.file.FlatFileItemWriter;
import org.springframework.batch.item.file.transform.BeanWrapperFieldExtractor;
import org.springframework.batch.item.file.transform.DelimitedLineAggregator;
import org.springframework.core.io.FileSystemResource;

/**
 * Builds the writer that turns each Item32AData entity into a CSV row.
 */
public final class Item32ACsvWriterFactory {

    private Item32ACsvWriterFactory() {
    }

    public static FlatFileItemWriter<Item32AData> create(String outputPath) {
        FlatFileItemWriter<Item32AData> writer = new FlatFileItemWriter<>();
        writer.setResource(new FileSystemResource(outputPath));
        writer.setHeaderCallback(w -> w.write("ReportingDate,TotalNrTrades,TotalNrReports"));

        BeanWrapperFieldExtractor<Item32AData> fieldExtractor = new BeanWrapperFieldExtractor<>();
        fieldExtractor.setNames(new String[] {"reportingDate", "totalNrTrades", "totalNrReports"});

        DelimitedLineAggregator<Item32AData> lineAggregator = new DelimitedLineAggregator<>();
        lineAggregator.setDelimiter(",");
        lineAggregator.setFieldExtractor(fieldExtractor);

        writer.setLineAggregator(lineAggregator);
        return writer;
    }
}
'''

# --------------------------------------------------------------------------
# source/src/main/resources
# --------------------------------------------------------------------------

FILES["source/src/main/resources/application.yml"] = r'''spring:
  application:
    name: batch-processing-demo

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

component-config:
  kududb:
    control-refit-schema: PUBLIC
    transc-schema: PUBLIC

  item32:
    item32aproperties:
      initial-total-trades-new: 0
      initial-total-trades-all: 0

app:
  jobs:
    t32a:
      end-period: "2026-03-31"
      reporting-date: "2026-04-30"
  output:
    t32a-csv: output/item32a-output.csv
'''

FILES["source/src/main/resources/data.sql"] = r'''INSERT INTO opr_data (actntp, rptgtmstmpdt) VALUES ('NEWT', '2026-01-15');
INSERT INTO opr_data (actntp, rptgtmstmpdt) VALUES ('NEWT', '2026-02-10');
INSERT INTO opr_data (actntp, rptgtmstmpdt) VALUES ('POSC', '2026-03-01');
INSERT INTO opr_data (actntp, rptgtmstmpdt) VALUES ('MODI', '2026-03-05');
INSERT INTO opr_data (actntp, rptgtmstmpdt) VALUES ('NEWT', '2026-04-01');

INSERT INTO record_status (receiveddt) VALUES ('2026-01-10');
INSERT INTO record_status (receiveddt) VALUES ('2026-02-20');
INSERT INTO record_status (receiveddt) VALUES ('2026-03-15');
INSERT INTO record_status (receiveddt) VALUES ('2026-04-05');
'''

FILES["source/src/main/resources/schema.sql"] = r'''DROP TABLE IF EXISTS opr_data;
CREATE TABLE opr_data (
    actntp       VARCHAR(10) NOT NULL,
    rptgtmstmpdt DATE        NOT NULL
);

DROP TABLE IF EXISTS record_status;
CREATE TABLE record_status (
    receiveddt DATE NOT NULL
);
'''

# --------------------------------------------------------------------------
# source/src/test/java
# --------------------------------------------------------------------------

FILES["source/src/test/java/com/sixgroup/refit/observability/batch/Item32ABatchConfigTest.java"] = r'''package com.sixgroup.refit.observability.batch;

import com.sixgroup.refit.observability.config.DatasourceSchemaProperties;
import com.sixgroup.refit.observability.config.Item32Properties;
import com.sixgroup.refit.observability.sql.Item32ADataFinderService;
import org.junit.jupiter.api.Test;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.test.JobLauncherTestUtils;
import org.springframework.batch.test.context.SpringBatchTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Boots only the T32A batch slice (reader = SQL query via
 * {@link Item32ADataFinderService}, writer = CSV) against H2.
 */
@SpringBatchTest
@SpringBootTest(classes = {
        Item32ABatchConfigTest.TestConfig.class,
        Item32ABatchConfig.class,
        Item32ADataFinderService.class
})
@EnableConfigurationProperties({Item32Properties.class, DatasourceSchemaProperties.class})
@TestPropertySource(properties = {
        "component-config.kududb.control-refit-schema=PUBLIC",
        "component-config.kududb.transc-schema=PUBLIC",
        "component-config.item32.item32aproperties.initial-total-trades-new=0",
        "component-config.item32.item32aproperties.initial-total-trades-all=0",
        "app.output.t32a-csv=target/test-output/item32a-output.csv"
})
class Item32ABatchConfigTest {

    @EnableAutoConfiguration
    static class TestConfig {
    }

    @Autowired
    private JobLauncherTestUtils jobLauncherTestUtils;

    /**
     * opr_data/record_status are already seeded by the app's own
     * schema.sql/data.sql (on the test classpath via src/main/resources),
     * which yield totalNrTrades=3 and totalNrReports=3 for endPeriod
     * 2026-03-31 — see those files for the raw rows.
     */
    @Test
    void readerRunsTheQueryAndWriterProducesTheCsv() throws Exception {
        JobParameters jobParameters = new JobParametersBuilder()
                .addString("endPeriod", "2026-03-31")
                .addString("reportingDate", "2026-04-30")
                .toJobParameters();

        JobExecution execution = jobLauncherTestUtils.launchJob(jobParameters);

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        List<String> lines = Files.readAllLines(Path.of("target/test-output/item32a-output.csv"));
        assertThat(lines).containsExactly(
                "ReportingDate,TotalNrTrades,TotalNrReports",
                "2026-04-30,3,3");
    }
}
'''


def generate_batch_project(target=None, overwrite=False):
    """Writes the rft-observability-item-batch project under `target`.

    Used both by this script's CLI and by `crud_generator.cli` (--batch).
    Raises DefinitionError instead of exiting so callers can report it
    uniformly with the rest of the generator's error handling.
    """
    target_path = Path(target) if target else Path(DEFAULT_TARGET)

    if target_path.exists() and any(target_path.iterdir()) and not overwrite:
        raise DefinitionError(
            f"El directorio '{target_path}' ya existe y no esta vacio "
            "(usa --force para sobrescribirlo)."
        )

    for rel_path, content in FILES.items():
        dest = target_path / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8", newline="\n")

    return str(target_path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "target",
        nargs="?",
        default=DEFAULT_TARGET,
        help="directory to generate the project into (default: %(default)s)",
    )
    parser.add_argument("--force", action="store_true", help="overwrite files that already exist")
    args = parser.parse_args()

    try:
        target = generate_batch_project(args.target, overwrite=args.force)
    except DefinitionError as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)

    print(f"Proyecto {target} generado con exito, bajo '{target}/'.")
    print("\nNext steps:")
    print(f"  cd {target}/source")
    print("  mvn -q test")
    print("  mvn spring-boot:run")


if __name__ == "__main__":
    main()
