apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rft-devtools-kafka-cucumber-main
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: shared-kafka-platform
spec:
  project: default
  source:
    repoURL: git@github.com:juanfranciscofernandezherreros/devtools-kafka.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-shared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
